Fix `make` error in OSX.
ext/semacode.c:61:3: error: call to undeclared function 'iec16022init'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

The fix is to declare the function in the C header file so that it is recognized